// Script:    TesteTabuleiro.script
// Autor:     eav - Eduardo Alberto Verdeja
// Data:      2/out/2014
// Propósito: Testar superficialmente o módulo tabuleiro
//

== Inicializar valores
=declararparm   FaltouMemoria       	int 0
=declararparm   OK                  	int 1
  
== Criar e destroi Estado
=criaestado 1 OK  
=destruirestado 1 OK

== Cria estado
=criaestado 1 OK

== Obtem os menus do estado
=getmenus 1 OK

== Obtem o tabuleiro do estado
=gettabuleiro 1 OK