// Script:    TesteTabuleiro.script
// Autor:     eav - Eduardo Alberto Verdeja
// Data:      2/out/2014
// Propósito: Testar superficialmente o módulo tabuleiro
//

== Inicializar valores
=declararparm   str0    string  "abcdefg"
=declararparm   str1    string  "qwerty"
=declararparm   str2    string  "xxx"
=declararparm   str3    string  "xpto"
=declararparm   str4    string  "???"
=declararparm   str5    string  "pera"

=declararparm   OK                      int 0
=declararparm   FaltouMemoria       	int 1
=declararparm	  NaoEhCasa				int 2
=declararparm   MovimentoInvalido       int 3
=declararparm   TabuleiroInvalido   	int 4
=declararparm   SemSolucao   			int 5

== Sequencia Criar-destruir no Tabuleiro
=criartab 1 10 10 str0 OK
=destruirtab 1 OK
=criartab 2 10 10 str0 OK
=destruirtab 2 OK
=destruirtab 3 OK
=recuperar
=criartab 1 10 10 str0 OK

== Posso sair do tabuleiro ?
=podeircima 1 0 OK
=recuperar
=andarcima 1 OK
=recuperar
=podeiresquerda 1 0 OK
=recuperar
=andaresquerda 1 OK
=recuperar
=podeircima 1 1 OK
=recuperar
=podeiresquerda 1 1 OK
=recuperar

== Editor pode andar em paredes
=podeirdireita 1 0 OK
=podeirbaixo 1 0 OK

== Jogador não pode andar em paredes
=podeirdireita 1 1 OK
=recuperar
=podeirbaixo 1 1 OK
=recuperar
=podeirdireita 1 1 MovimentoInvalido
=podeirbaixo 1 1 MovimentoInvalido

== Ir para o outro canto
=andarbaixo 1 OK
=andarbaixo 1 OK
=andarbaixo 1 OK
=andarbaixo 1 OK
=andarbaixo 1 OK
=andarbaixo 1 OK 
=andarbaixo 1 OK
=andarbaixo 1 OK
=andarbaixo 1 OK
=andardireita 1 OK
=andardireita 1 OK
=andardireita 1 OK
=andardireita 1 OK
=andardireita 1 OK
=andardireita 1 OK
=andardireita 1 OK
=andardireita 1 OK
=andardireita 1 OK

== Posso sair do tabuleiro ?
=podeirbaixo 1 0 OK
=recuperar
=andarbaixo 1 OK
=recuperar
=podeirdireita 1 0 OK
=recuperar
=andardireita 1 OK
=recuperar
=podeirbaixo 1 1 OK
=recuperar
=podeirdireita 1 1 OK
=recuperar

== Editor pode andar em paredes
=podeiresquerda 1 0 OK
=podeircima 1 0 OK

== Jogador não pode andar em paredes
=podeiresquerda 1 1 OK
=recuperar
=podeircima 1 1 OK
=recuperar
=podeiresquerda 1 1 MovimentoInvalido
=podeircima 1 1 MovimentoInvalido

== Voltar para (0,0)
=andaresquerda 1 OK
=andaresquerda 1 OK
=andaresquerda 1 OK
=andaresquerda 1 OK
=andaresquerda 1 OK
=andaresquerda 1 OK
=andaresquerda 1 OK
=andaresquerda 1 OK
=andaresquerda 1 OK
=andarcima 1 OK
=andarcima 1 OK
=andarcima 1 OK
=andarcima 1 OK
=andarcima 1 OK
=andarcima 1 OK
=andarcima 1 OK
=andarcima 1 OK
=andarcima 1 OK
=andarcima 1 MovimentoInvalido

== Sequencia PoeX
=poeparede 1 OK
=poechao 1 OK
=poeinicio 1 OK
=poefim 1 OK

== Obtem a posicao do jogador
=posicaojogador 1 OK

== Obtem o tipo da casa
=gettipocasa 1 OK

== Obtem altura do tabuleiro
=getaltura 1 OK

== Obtem largura do tabuleiro
=getlargura 1 OK

== Obtem nome do tabuleiro
=getnome 1 OK

== Criar caminho
=poechao 1 OK
=andarbaixo 1 OK
=poechao 1 OK
=andarbaixo 1 OK
=poechao 1 OK
=andardireita 1 OK
=poechao 1 OK

== Criar um caminho disconexo do anterior
=andardireita 1 OK
=andardireita 1 OK
=poechao 1 OK
=andarcima 1 OK
=poechao 1 OK
=andaresquerda 1 OK
=poechao  1 OK

== Tenta validar (sem inicio/final)
=validartab 1 OK
=recuperar
=validartab 1 TabuleiroInvalido

== Criar inicio e final disconexo
=poefim 1 OK
=andaresquerda 1 OK
=andaresquerda 1 OK
=andaresquerda 1 OK
=recuperar
=andarcima 1 OK
=poeinicio 1 OK

== Valida tabuleiro
=validartab 1 OK

== Solucionar tabuleiro
=solucionartab 1 OK
=recuperar
=solucionartab 1 SemSolucao

== Conecta inicio e fim
=andarbaixo 1 OK
=andarbaixo 1 OK
=andardireita 1 OK
=andardireita 1 OK
=poechao 1 OK

== Solucionar tabuleiro
=solucionartab 1 OK

== Salva o tabuleiro
=salvartab 1 OK

== Carrega o tabuleiro
=carregartab 1 OK

